### ISSUE TITLE
building under windows with msys2

### ISSUE THREAD

**Issue by lmascelli** [SpartanJ/eepp#19]
hello,
to get it compile under windows 10 with msys2 updated and mingw-w64-gcc toolchain i had to apply this edits to the premake5.lua:
- add a  `defines { "WINVER=0x0602" }`
- edit the `mklink` occurrences with `cmd //c mklink` and the same for `ver`

**Comment by SpartanJ** [comment]
Thanks for letting me know, I think I have never built using msys2, so I don't know exactly what's the difference. Last week I used [this](https://github.com/skeeto/w64devkit) package and worked fine, but I usually cross-build from Linux the Windows builds using mingw64.

**Comment by lmascelli** [comment]
maybe it's just something wrong in my msys2 configuration. i reported it in case someone else run in the same issue. not sure if it deserve a pr

**Comment by SpartanJ** [comment]
Sure, thanks!

**Comment by SpartanJ** [comment]
I applied some of the suggested changes, added the definition of the WINVER, and I just checked if the environment is MSYS to use ln instead of `mklink` for the commands. That seems to do the job. But I encountered some very weird problems while compiling, it seems that some very large commands fail (usually the linking or the static lib generation with ar), but the commands are fine, if I copy and paste the printed command it actually works, it must be something with the encoding or something like that. I'm unfamiliar with MSYS2, and I don't know where to ask what the hell is happening, and it's probably an issue with my environment.

**Comment by lmascelli** [comment]
i tried to build the project encountering no errors. the step i followed are those:
```
git clone --recurse-submodules --depth=1 https://github.com/SpartanJ/eepp
cd eepp
mingw64.bat
premake5 --with-static-eepp gmake2
make -C make/windows -j16
```

**Comment by SpartanJ** [comment]
Great, we can close the issue. Thanks for trying it out.
