### ISSUE TITLE
Add VTE widget

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/eepp#26]
Add your own virtual terminal emulator widget.

**Comment by SpartanJ** [comment]
>  Imagine someone someday will build a terminal emulator in eepp using said widget.

He was asking for something different. What you mention is already supported. The eepp terminal emulator is a module that acts as a VTE library and it has integration with the eepp UI library. If you want to use it with the eepp UI you just need to use the [UITerminal](https://github.com/SpartanJ/eepp/blob/develop/src/modules/eterm/include/eterm/ui/uiterminal.hpp) widget. You can also use the terminal emulator directly by consuming the [TerminalDisplay](https://github.com/SpartanJ/eepp/blob/develop/src/modules/eterm/include/eterm/terminal/terminaldisplay.hpp) class, the [eterm](https://github.com/SpartanJ/eepp/blob/develop/src/tools/eterm/eterm.cpp) terminal uses that directly. So that application already exists, I just don't publish it because it does not bring anything new to the table, there are plenty of capable terminals out there, and also ecode can be used exclusively as a terminal, try starting ecode in terminal mode with `ecode -t`.

**Comment by yh15kla9** [comment]
I don't think you have your own terminal emulator. You just call the platform's native terminal emulator. Windows Terminal in the case of Windows. What do you call on Linux? Xterm? I'm really curious.

**Comment by yh15kla9** [comment]
@Alex2772 Does your library have a VTE widget?

**Comment by SpartanJ** [comment]
> I don't think you have your own terminal emulator. You just call the platform's native terminal emulator. Windows Terminal in the case of Windows. What do you call on Linux? Xterm? I'm really curious.

No. You're wrong, as I already explained eepp implements its own terminal emulator based on the `st` VTE implementation, it does not depend on Windows Terminal nor xterm or any other application. Most of the implementation can be found [here](https://github.com/SpartanJ/eepp/blob/develop/src/modules/eterm/src/eterm/terminal/terminalemulator.cpp). The eepp terminal only needs a PTY. The original issue was referring to implement a PTY layer for old Windows / use a library for it, because old Windows do not provide an API for it, modern Windows provide the kernel function `CreatePseudoConsole`.
