### ISSUE TITLE
`clang++` doesn't support the `-s` switch

### ISSUE THREAD

**Issue by iahung2** [SpartanJ/eepp#29]
It will spit out gazillion of warnings like this when building in release mode:

`clang++: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]`

Note: I'm on Windows with MSYS2 CLANG64.

**Comment by iahung2** [comment]
https://github.com/SpartanJ/eepp/blob/5975174e48defd88b8bcd8384bf58b4c98d57f88/premake5.lua#L345

**Comment by iahung2** [comment]
https://github.com/SpartanJ/eepp/blob/5975174e48defd88b8bcd8384bf58b4c98d57f88/premake4.lua#L623

**Comment by iahung2** [comment]
These warnings are not harmless. I found they are slowing the compilation process down significantly.

**Comment by SpartanJ** [comment]
> The problem seems to be because LLVM Clang itself doesn't support the -s switch. MSYS2 is not related here.
Yes, I don't support MSYS2 OR clang on Windows, I have never built the project with clang on Windows.

Since I don't have that environment working could you try to apply a fix and tell me if it works?

In `premake5.lua` change line 344 from:
`filter { "configurations:release*", "action:not vs*", "system:not macosx" }`
to
`filter { "configurations:release*", "action:not vs*", "system:not macosx", "system:not windows" }`

That should be enough to skip it.

**Comment by iahung2** [comment]
> > The problem seems to be because LLVM Clang itself doesn't support the -s switch. MSYS2 is not related here.
> 
> Yes, I don't support MSYS2 OR clang on Windows, I have never built the project with clang on Windows.
> 
> Since I don't have that environment working could you try to apply a fix and tell me if it works?
> 
> In `premake5.lua` change line 344 from: `filter { "configurations:release*", "action:not vs*", "system:not macosx" }` to `filter { "configurations:release*", "system:not macosx", "system:not windows" }`
> 
> That should be enough to skip it.

MSYS2 UCRT64 (GCC based) does support the `-s` switch. Doing so will skip the `-s` switch for any compilers target Windows.

**Comment by iahung2** [comment]
Well, since both MSYS2 and LLVM Clang are not supported on Windows, I will handle it myself by editing `premake5.lua` manually.
