### ISSUE TITLE
Migrate to CMake

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/eepp#49]
Please do it. Thank you.

**Comment by SpartanJ** [comment]
No, sorry, I'll never maintain a CMake project for my personal open-source projects, I don't like it and I don't enjoy using it, so I'll avoid it. I do accept collaborators for maintaining a CMake project for [some](https://github.com/SpartanJ/efsw) of my [projects](https://github.com/SpartanJ/SOIL2) but for eepp this is not possible due to the complexity of the multi-platform build to maintain. I'll probably switch to a different build system in the future but it won't be CMake, that's 100% sure.
