### ISSUE TITLE
Add Windows on ARM builds

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/eepp#65]
You are cross compiling anyway. Try something fun.

**Comment by chatchoi** [comment]
This is a prebuilt binary of SDL2 for ARM64 Windows that you could use:

https://github.com/mmozeiko/build-sdl2/releases

**Comment by SpartanJ** [comment]
Problem is not SDL2 (I can build it during the CI, as I'm already doing in some cases), but I have no simple way of adding an arm64 build from the current pipe configuration since there are no aarch64 mingw-w64 binaries available in Ubuntu, also I don't have the hardware to test the builds and I don't like that, plus arm64 windows is extremely niche these days. I'll add it but I have no rush.

**Comment by chatchoi** [comment]
You will have to wait for GCC 15 to have a GCC-based MinGW-w64 that can target ARM64 Windows. But llvm-mingw has always supported ARM64 Windows and it has prebuilt binaries for Ubuntu, too.

https://github.com/mstorsjo/llvm-mingw/releases

**Comment by SpartanJ** [comment]
> https://github.com/mmozeiko/build-sdl2/releases

Sadly that is an MSVC release so it was not useful, I had to do a manual build.

> https://github.com/mstorsjo/llvm-mingw/releases

I ended up using this, nightly will fetch the ubuntu package, unpack it, add the bin path of that package to `PATH` and request an arm64 build to eepp scripts. Really hackish build but works.
