### ISSUE TITLE
Support SDL_Image

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/eepp#68]
More choices are better. SOIL2 is still the default, like the story of MojoAL vs OpenAL, MbedTLS vs OpenSSL.

**Comment by Curculigo** [comment]
I find out that the developer deliberately try to not using any of the SDL2 auxiliary libraries. For example, freetype2 and harfbuzz are used directly instead of SDL_ttf. So I know this proposal will not be accepted.

**Comment by SpartanJ** [comment]
SDL_image cannot be used as a drop in replacement of SOIL2, they do different things, SDL_image is equivalent to one of the components of SOIL2, stb_image. Also SDL_image is a *fat* dependency because it depends on many other libraries, that's why I would never use it. SOIL2 handles all the OpenGL complexity and that is the real reason to use it.
