### ISSUE TITLE
[premake] Projects with same output file, but with different target platform

### ISSUE THREAD

**Issue by Jarod42** [SpartanJ/eepp#74]
According to https://github.com/jimon/premake-ninja/issues/40
several projects generate output with same name and same location independently of the platform,
as eepp-external-shader

```
** Warning: eepp-external-shader_debug_x86_64 and eepp-external-shader_debug_x86 both generate differently ../../bin/eepp-external-shader-debug. Ignoring eepp-external-shader_debug_x86
Generated make/linux/build_eepp-external-shader_debug_x86.ninja...
```
Whereas ninja warns about that, other generators might also have issue when building the target for different platform without previous clean/rebuild.

**Comment by SpartanJ** [comment]
Hi! I have never tried to build with the CMake and Ninja projects so I wasn't aware if they worked. I applied a very simple patch to only generate projects for the current platform when used with ninja, so now builds without warnings.
Since you're here I would like to request you some help with the CMake project generated, it *almost* works flawlessly but has a single bug, let me explain it to you:

After the shared library is built I'm adding a couple of symbolic links of the library built in the `bin` folder of the project where all the binaries reside, since it's needed to run them, the script does this:

```lua
function postsymlinklib(src_path, dst_path, lib, arch)
        -- ...
	filter { "configurations:release*", "not system:windows", arch }
		postbuildcommands { "ln -sf \"" .. src_path .. "lib" .. lib .. "." .. get_dll_extension() .. "\" \"" .. dst_path .. "\"" }
	filter { "configurations:debug*", "not system:windows", arch }
		postbuildcommands { "ln -sf \"" .. src_path .. "lib" .. lib .. "-debug." .. get_dll_extension() .. "\" \"" .. dst_path .. "\"" }
end
```

It basically calls to `ln -sf`, the problem is that CMakes generates the following:
```cmake
add_custom_command(TARGET eepp-shared PRE_LINK
  COMMAND $<$<CONFIG:x86_debug>:ln -sf \"/home/programming/eepp/libs/linux/x86/libeepp-debug.so\" \"/home/programming/eepp/bin/\">
  COMMAND $<$<CONFIG:x86_debug>:ln -sf \"/home/programming/eepp/libs/linux/x86/libeepp-debug.so\" \"/home/programming/eepp/bin/unit_tests/\">
  COMMAND $<$<CONFIG:x86_64_release>:ln -sf \"/home/programming/eepp/libs/linux/x86_64/libeepp.so\" \"/home/programming/eepp/bin/\">
  COMMAND $<$<CONFIG:x86_64_release>:ln -sf \"/home/programming/eepp/libs/linux/x86_64/libeepp.so\" \"/home/programming/eepp/bin/unit_tests/\">
  COMMAND $<$<CONFIG:x86_64_debug>:ln -sf \"/home/programming/eepp/libs/linux/x86_64/libeepp-debug.so\" \"/home/programming/eepp/bin/\">
  COMMAND $<$<CONFIG:x86_64_debug>:ln -sf \"/home/programming/eepp/libs/linux/x86_64/libeepp-debug.so\" \"/home/programming/eepp/bin/unit_tests/\">
  COMMAND $<$<CONFIG:arm64_release>:ln -sf \"/home/programming/eepp/libs/linux/arm64/libeepp.so\" \"/home/programming/eepp/bin/\">
  COMMAND $<$<CONFIG:arm64_release>:ln -sf \"/home/programming/eepp/libs/linux/arm64/libeepp.so\" \"/home/programming/eepp/bin/unit_tests/\">
  COMMAND $<$<CONFIG:arm64_debug>:ln -sf \"/home/programming/eepp/libs/linux/arm64/libeepp-debug.so\" \"/home/programming/eepp/bin/\">
  COMMAND $<$<CONFIG:arm64_debug>:ln -sf \"/home/programming/eepp/libs/linux/arm64/libeepp-debug.so\" \"/home/programming/eepp/bin/unit_tests/\">
  COMMAND $<$<CONFIG:x86_release>:ln -sf \"/home/programming/eepp/libs/linux/x86/libeepp.so\" \"/home/programming/eepp/bin/\">
  COMMAND $<$<CONFIG:x86_release>:ln -sf \"/home/programming/eepp/libs/linux/x86/libeepp.so\" \"/home/programming/eepp/bin/unit_tests/\">
)
```

Which generates the following error:
```
/bin/sh: -c: line 1: syntax error near unexpected token `newline'
/bin/sh: -c: line 1: `"\$<1:ln" -sf "/home/programming/eepp/libs/linux/x86_64/libeepp-debug.so" "/home/programming/eepp/bin/">'
make[2]: *** [CMakeFiles/eepp-shared.dir/build.make:6880: /home/programming/eepp/libs/linux/x86_64/libeepp-debug.so] Error 2
```

I tried manually changing the command with a few variations with no success. I'm very unfamiliar with CMake so I'm not sure what's happening.

Now that I tested both project generation, Ninja seems really interesting because of two things:
1. Project files are generated much faster than `gmake2` (`ninja` takes ~1s vs `gmake2` ~2.6s).
2. Project build time is around 20% faster, it's a considerable gain!

On the other side CMake seems to be slower for project generation (~4.6s), but having support for it would be nice since people have asked for it many times, but I always decline it because I personally dislike it and I don't want to deal with it, this would be an ideal solution (at least for me).

Any help will be appreciated.
Also thanks for working on these projects, they are very nice!

**Comment by Jarod42** [comment]
There is currently a bug in premake-cmake for pre/postbuild command
We have issue with `add_custom_command` with expression generator :-/
Working on it.

**Comment by SpartanJ** [comment]
Excellent, it's working, thank you very much!
