### ISSUE TITLE
SuperTux's sdl video system

### ISSUE THREAD

**Issue by chadchoi** [SpartanJ/eepp#77]
I don't know what it is. The game on my hardware has 4 video systems: auto, sdl, opengl20, and opengl33. I only know that switching to the sdl video system reduced tearing when playing the game on my computer. I guess that it's SDL's abstracted graphics API (instead of calling OpenGL directly like opengl20 and opengl33). Does eepp has an option like that? It seems that it's calling OpenGL directly. I only see OpenGL 2, OpenGL 3, OpenGL 3 Core Profile, and OpenGL ES 2 in `Renderer Version` menu.

p/s: I only asked because I'm curious. I currently have no tearing or other problems with eepp applications (ecode, to be clear).

**Comment by SpartanJ** [comment]
> I don't know what it is. The game on my hardware has 4 video systems: auto, sdl, opengl20, and opengl33. I only know that switching to the sdl video system reduced tearing when playing the game on my computer.

That's probably using SDL software renderer.

> I only know that switching to the sdl video system reduced tearing when playing the game on my computer.

Have you tried enabling VSync in that game? If you want VSync in ecode it's in `Windows -> Renderer -> VSync`, it's disabled in all platforms by default except macOS. VSync adds input latency so I try to avoid it (in macOS is less of a problem because any modern mac will have a 120hz monitor, so it's only a max 8ms latency, and vsync goes better with the compositor there).

> Does eepp has an option like that? 

No, eepp does not provide a software renderer, it's not an option. But you could use eepp with a software-renderer if you're using Mesa without drivers, it will fallback to LLVM-pipe software renderer, that's how it works on Haiku for example (which does not support hardware 3D acceleration).

> p/s: I only asked because I'm curious. I currently have no tearing or other problems with eepp applications (ecode, to be clear).

No problem, but remember: questions go in [Discussions](https://github.com/SpartanJ/eepp/discussions).
