### ISSUE TITLE
Vulkan

### ISSUE THREAD

**Issue by chadchoi** [SpartanJ/eepp#78]
What do you think about it? On Phoronix forums, Vulkan is kind of the future and OpenGL is dead. My hardware doesn't even support Vulkan, so I don't care about it much. But I think there are people that want Vulkan. I have been reading the Phoronix forums for a while, and thanks to that, I know about Zink. OpenGL applications like the ones using eepp can still run on Zink.

**Comment by SpartanJ** [comment]
Vulkan is not particularly valuable for 2D applications, it does not bring any benefits over a modern OpenGL version, but it adds a lot of complexity. Vulkan and OpenGL are not the same thing, Vulkan does not replace OpenGL, Vulkan is low-level API and OpenGL acts as high level abstraction of it (hence the existence of Zink), OpenGL wont disappear, it might disappear the support at hardware level (in a long future I would say) but there will be always an available translation layer for OpenGL to Vulkan, given that they cover different needs. Adding a Vulkan renderer in eepp would be a massive job, so before doing that I would probably just work in a new library from scratch or I would use an GPU abstraction API (for example [SDL3 GPU API](https://wiki.libsdl.org/SDL3/CategoryGPU) or [bgfx](https://github.com/bkaradzic/bgfx)).

> Vulkan is kind of the future and OpenGL is dead

That is just mob mentality, not the reality. It's true that this could be true for big 3D engines but it does not apply for something like a 2D simple app. Big 3D engines have *very* different requirements and needs and you need to squeeze the GPU capabilities to its maximum potential, so 3D engine developers will and probably should use Vulkan if they want some multi-platform support (big engines very rarely use Vulkan as the main renderer on Windows, they just use DX12, and on macOS they need to use Metal, so market is pretty framented right now).

> But I think there are people that want Vulkan.

People tend to want the new shiny thing just because of it. Sometimes it's justified sometimes it's not...
