### ISSUE TITLE
There are still leftover files when running make clean

### ISSUE THREAD

**Issue by chadchoi** [SpartanJ/eepp#81]
eepp/libs/windows/x86_64/eepp*.lib

**Comment by SpartanJ** [comment]
Are you sure you used the config parameter you needed to delete the files?
`make clean` will use the default config, usually `debug_x86_64`, but if you built for `release_x86_64` it will not clean up the files. If this fails I cannot fix it anyways because this is generated by premake and it's not customisable, but I've not seen it fail.

**Comment by chadchoi** [comment]
I'm lazy and as I'm only build in release mode, I keep `make -C make/windows config=release_86_64` in a text file and will copy/paste it when needed. So, I'm always specify the config parameter. I can confirm that everything is cleaned up, except these `.lib` files.
